title: "Ramiro Estrella Pernetti"
description: "Proyectos, tecnología y blog personal"
baseurl: "/ramiro_estrella_pernetti" # Subdirectorio del repositorio
url: "https://proxmy.github.io" # URL principal del sitio
theme: minima
plugins:
  - jekyll-feed
markdown: kramdown
author:
  name: "Ramiro Estrella Pernetti"
  email: "tomasestrellaramiro@gmail.com"

