title: "Ramiro Estrella Pernetti"
description: "Experto en redes, microinformática y administración de servidores. Descubre mis proyectos y experiencia profesional."
permalink: pretty
baseurl: "/ramiro_estrella_pernetti" # Si tu repositorio se llama "ramiro_estrella_pernetti"
url: "https://proxmy.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
markdown: kramdown
author:
  name: "Ramiro Estrella Pernetti"
  email: "tomasestrellaramiro@gmail.com"
  social:
    linkedin: "https://linkedin.com/in/ramiro-estrella"
    github: "https://github.com/proxmy"
